version: "3.8"

services:
  submission-service:
    build: ./submission
    ports:
      - "3003:3003"
    volumes:
      - ./submission:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - NODE_ENV=production

  problem-service:
    build: ./problem
    ports:
      - "3001:3001"
    volumes:
      - ./problem:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

  evaluator-service:
    build: ./evaluator
    ports:
      - "3000:3000"
    volumes:
      - ./evaluator:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - NODE_ENV=production

  socket-service:
    build: ./socket
    ports:
      - "3002:3002"
    volumes:
      - ./socket:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - NODE_ENV=production

  job-search-service:
    build: ./job-search
    ports:
      - "3004:3004"
    volumes:
      - ./job-search:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - NODE_ENV=production

  blog-service:
    build: ./blog
    ports:
      - "3005:3005"
    volumes:
      - ./blog:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - NODE_ENV=production

  merchandise-service:
    build: ./merchandise
    ports:
      - "3006:3006"
    volumes:
      - ./merchandise:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - NODE_ENV=production

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
